### ISSUE TITLE
how to avoid Buffer Shortage error?

### ISSUE THREAD

**Issue by AnubisCode** [gamestdio/colyseus.js#1]
after some time playing TANX demo, this error occurs
`Uncaught Error: BUFFER_SHORTAGE`

and also when I run my demo, after a couple minutes but not always:
```
WebSocket connection failed: Error during WebSocket handshake: Unexpected response code: 502  
colyseus.js:4948
```

how to avoid this error in function uint8?
`throw new BufferShortageError();`

**Comment by endel** [comment]
Hi @AnubisCode, 

These two errors you described are not related with each other. 

The `Uncaught Error: BUFFER_SHORTAGE` happens on the [TANX demo](https://playcanvas.com/project/367035/overview/tanxcolyseus) because it's hosted on a free Heroku process, and after a while without interaction the process is shut down, causing the `BUFFER_SHORTAGE` error.

The response code `502` means unexpected response / bad gateway - so you're server is most likely not to be running when you get this error.

Hope this helps,
Cheers

**Comment by AnubisCode** [comment]
Thanks for your reply!
