### ISSUE TITLE
Timeline implementation

### ISSUE THREAD

**Issue by Ulydev** [gamestdio/colyseus.js#6]
Hello endel, thanks for your work on Colyseus. I've found it really useful so far.
I'm making a fast-paced multiplayer game and I'd need to use timelines to interpolate snapshots. The Colyseus server has a timeframe dependency, but not the Colyseus.js client. Also it seems that the server uses clock-timer.js while the client uses clock.js. There are some dependencies that are different on both sides, I don't understand why.
Also, would you happen to know how one could synchronise the clock between client/server for time-based events, e.g. shooting? If I understand correctly, I'd need to send a timestamp along with the shooting aim and check for the coordinates on the server-side using a snapshot from the past (associated with the timestamp)?

I'm sorry for asking such basic questions, but I'm pretty new to networking.
Thanks in advance for your help!

**Comment by endel** [comment]
Hey @Ulydev,

Thanks for checking out the project.

This Timeline system is still a bit experimental. Currently, it's only available in the server-side to allow you to validate some user actions. For instance, given you have 2 clients and one of them is slightly delayed due to some network issue. The delayed client will have a different local state, and a different [remoteClock](https://github.com/gamestdio/colyseus.js/blob/master/src/Room.ts#L18) time (which holds the current time for the Room on the server). 

To validate an important action, such as a shoot, you can send to the server the `remoteClock.currentTime` in addition to your command. You can then rewind the state in the server-side and check if the action is valid or not.

Unfortunately, I don't have a practical example with real code to show to you.

About the clocks, the client only has a simple ticker. IMHO it only makes sense to have `setTimeout`/`setInterval` with time precision in the server-side - which will eventually change the state of the Room, and be broadcasted to all clients - the clients then are just a visual representation of what is happening on the server. You can require `clock-timer.js`in your client by your own if you want to.

Please don't hesitate to ask questions here or in the [gitter channel](https://gitter.im/gamestdio/colyseus)!
Cheers!

**Comment by Ulydev** [comment]
Thank you for clearing it up!
